name: 'Setup HashiCorp Nomad'
description: 'Sets up HashiCorp Nomad in your GitHub Actions workflow.'
author: 'Escapace'
inputs:
  nomad-version:
    description: 'The version of Nomad to install. Instead of full version string you can also specify a semantic version range (for example `^1.3.1`) to install the latest version satisfying the constraint. A value of `latest` will install the latest version of Nomad. Defaults to `latest`.'
    default: 'latest'
    required: false
runs:
  using: 'node16'
  main: 'lib/cjs/index.cjs'
branding:
  icon: 'terminal'
  color: 'purple'
